print ('(a)')
print ('\tBILHETE')
print ('')
print ('\tSe tu me amas, ama-me baixinho')
print ('\tNão o grites de cima dos telhados')
print ('\tDeixa em paz os passarinhos')
print ('\tDeixa em paz a mim!')
print ('\tSe me queres,')
print ('\tenfim,')
print ('\ttem de ser bem devagarinho, Amada,')
print ('\tque a vida é breve, e o amor mais breve ainda')
print ('')
print ('\tMario Quintana')
print ('')
print ('(b)')
print ('\tBILHETE\n\n\tSe tu me amas, ama-me baixinho\n\tNão o grites de cima dos telhados\n\tDeixa em paz os passarinhos\n\tDeixa em paz a mim!\n\tSe me queres,\n\tenfim,\n\ttem de ser bem devagarinho, Amada,\n\tque a vida é breve, e o amor mais breve ainda\n\n\tMario Quintana')
